### ISSUE TITLE
Passing SafetyNet?

### ISSUE THREAD

**Issue by ph0t0shop** [HuskyDG/MagiskOnNox#3]
Is there any way to pass SafetyNet on Magisk using this repo?

**Comment by HuskyDG** [comment]
SafetyNet pass on emulator is impossible even on Android Virtual Device from Google. You are wrong if you think installing Magisk will pass SafetyNet unconditional. For SafetyNet, You're device must be certificated and implement hardware-backed attestation while emulator cannot implement these. Also Google will replace SafetyNet with Play Integrity soon.

**Comment by AndnixSH** [comment]
That's true. I don't get why people think you can pass safetynet on uncertificated emulators XD

**Comment by HuskyDG** [comment]
> That's true. I don't get why people think you can pass safetynet on uncertificated emulators XD

They even don't know how SafetyNet works.
They ask everywhere, on my Youtube channel, Telegram,... MagiskOnWSA repo

**Comment by AndnixSH** [comment]
You should filter the word when possible. I did a while back then on my YT channel but i deleted my channel for now

Even if you have SafetyNet fix module, it will not work no matter what

![image](https://user-images.githubusercontent.com/40742924/148677715-e3843339-c71f-46a5-97b5-1d08b2fb21fa.png)

**Comment by HuskyDG** [comment]
> You should filter the word when possible. I did a while back then on my YT channel but i deleted my channel for now
> 
> Even if you have SafetyNet fix module, it will not work no matter what
> 
> ![image](https://user-images.githubusercontent.com/40742924/148677715-e3843339-c71f-46a5-97b5-1d08b2fb21fa.png)

Yes, Even Emulator cannot pass basicIntegrity SafetyNet check. While it can on actual devices whaever your device is certificated or not

**Comment by AndnixSH** [comment]
> I dont think this is a stupid question,just before you work,many people say magisk is impossible to run at emulator,but you did it,so I believe nothing is impossible to your talented guys.

Maybe Magisk wasn't that hard.

Now to pass SafetyNet, emulators need to emulate bootloader and Hardware-backed Attestation with a key from real phone. Idk how it excatly works, i'm just assuming the key is read from motherboard. This will be a lot harder when it comes to security. I might be wrong

**Comment by HuskyDG** [comment]
If you device is not rooted and it is running stock rom then you can pass SafetyNet.
Root will make SafetyNet test fail both ctsprofile and basicintegrity.
Magisk introduce MagiskHide to hide Magisk from almost integrity system check / root detection.
MagiskHide is not meant for bypass SafetyNet.
MagiskHide is only meant: "Make sure all magisk modification are hidden and not trigger the SafetyNet check"
Since 2021, Google have enforced hardware attestation that check for boot verity state that make Magisk impossible to pass SafetyNet. If you unlock bootloader, you will fail ctsprofile check.
See full here: https://developer.android.com/training/safetynet/attestation
To pass SafetyNet with hardware attestation, you will use SafetyNet Fix to prevent gms from using hardware attestation so SafetyNet will fall back to Basic attestation which is easy to bypass, the minimal requirements is that you must pass ctsprofile check of SafetyNet test.

**Comment by HuskyDG** [comment]
You cannot fake SafetyNet, as the reason topjohnwu described here:

https://mobile.twitter.com/topjohnwu/status/1237830555523149824

**Comment by AndnixSH** [comment]
Oh i see, yeah SafetyNet is too strong. MagiskHide is all i need. No need safetynet bypass since most apps i use doesn't use it
